[SQUASH] Provide a shim for libui
Change-Id: I270905c3e9ba3500288454925f8c48e970f4925c

---
    From: Erfan Abdi <erfangplus@gmail.com>
    Date: Sun, 8 Sep 2019 15:04:55 +0430
    Subject: [PATCH] aura: ims: Make shim for libui

    P: GraphicBuffer::lock(uint32_t inUsage, void** vaddr);
    Q: GraphicBuffer::lock(uint32_t inUsage, void** vaddr, int32_t* outBytesPerPixel = nullptr, int32_t* outBytesPerStride = nullptr);
    Error: cannot locate symbol "_ZN7android13GraphicBuffer4lockEjPPv"

    Change-Id: I1c1fe66f3f73149ced601eae87b970ce392d50ee
---
    From: Quallenauge <Hamsi2k@freenet.de>
    Date: Sun, 22 Sep 2019 21:28:13 +0200
    Subject: [PATCH] cheryl: camera: Respect non-static member function calls.

    As stated in
    https://www.learncpp.com/cpp-tutorial/8-8-the-hidden-this-pointer/
    member functions contains a hidden parameter (a pointer of the current
    reference of teh object, aka "this"). This way the code knows in which
    context the member function is called. We have to resprect that behavior
    into our shims which otherwise crashes or lead to memory corruption.
    Change-Id: I68197ebafde8773fd73d7dafb9b2f1bae92ee170
---

Change-Id: I27d511340f0f2497bbeb2b046c18b66606610040